spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    # NON_KEYWORDS=USER옵션은 MySQL의 예약어인 USER 키워드를 비활성화 한다.
    url: "jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      # H2 콘솔 접속 활성화
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: dev
      # 아래 있는 설정들은 특정 Profile에 실행된다.

  application:
    name: library-app

  datasource:
    # ??????? ??? ? ??? ????
    driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc? ??? mysql? ????.
    url: jdbc:mysql://localhost/library
    username: root
    password: 1q2w3e4r!
    
  jpa:
    hibernate:
      # create: 기존 테이블이 있다면 삭제 후 다시 생성
      # create-drop: 스프링이 종료될 때 테이블을 모두 제거
      # update: 객체와 테이블이 다른 부분만 변경
      # validate: 객체와 테이블이 동일한지 확인
      # none: 별다를 조치를 하지 않는다.
      ddl-auto: none
    properties:
      hibernate:
        # JPA를 사용해 DB에 SQL을 날릴 때 SQL을 보여줄 것인가
        show_sql: true
        # SQL을 보여줄 때 예쁘게 포맷팅 할 것인가
        format_sql: true
        # dialect: 방언, 사투리
        # DB를 특정하면 조금씩 다른 SQL을 수정해준다.
        dialect: org.hibernate.dialect.MySQL8Dialect
